---
- hosts: all
  become: true
  tasks:
  
  - name: update repository index for Ubuntu
    apt:
      update-cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache pnd php packages for Ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: update repository index for CentOS
    dnf:
      update-cache: yes
    when: ansible_distribution == "CentOS"

  - name: install httpd and php packages for CentOS
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"
