---
- hosts: all
  become: true
  tasks:
  
  - name: update repository index 
    apt:
      update-cache: yes

  - name: install apache package
    apt:
      name: apache2
      state: latest

  - name: add php support
    apt: 
      name: libapache2-mod-php
      state: latest
