---
- hosts: all
  become: true
  tasks:

  - name: install apache pnd php packages for Ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update-cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install httpd and php packages for CentOS
    dnf:
      name: 
        - httpd
        - php
      state: latest
      update-cache: yes
    when: ansible_distribution == "CentOS"
