- name: add ssh key for grumpy
  authorized_key:
    user: grumpy
    key: "{{ lookup('file', '~/.ssh/ansible.pub') }}"

- name: generate sshd_config file from template
  tags: ssh
  template: 
    src: "{{ ssh_template_file }}" 
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd
